# Generated by Django 4.2.6 on 2024-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='is_state_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='is_state_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='is_state_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
